
[project]
name = "obsidian_to_bookstack"
version = "0.1.0"
description = ""
authors = [
    {name = "Jayden Pyles", email = "jpylesbusiness@gmail.com"},
]
dependencies = [
    "toml>=0.10.2",
]
requires-python = ">=3.10"
license = {text = "MIT"}
